name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install
        working-directory: ./

      - name: Rodar os testes
        run: npm test
        working-directory: ./
        # Ajuste feito em 21/09